---
title: "Untitled"
author: "Nicholas Borcherding"
date: '2023-01-13'
output: html_document
---

Trying to identify edit distances for candidate TCRs
```{r cars}
library(Seurat)
library(stringdist)
library(Trex)
conga <- readRDS("./data/processedData/conga_tfh_seuratObject.rds")
conga <- annotateDB(conga, chains = "TRB", edit.distance = 0)
conga <- annotateDB(conga, chains = "TRA", edit.distance = 0)

meta <- conga[[]]
meta <- meta[!is.na(meta$confirmation.seq),]
meta <- meta[order(meta$confirmation.seq),]

confirm.TCRA.gene <- as.vector(meta$TRAV)
confirm.TCRB.gene <- as.vector(meta$TRBV)
confirm.TCRA <- stringr::str_split(meta$CTaa, "_", simplify = TRUE)[,1]
confirm.TCRB <- stringr::str_split(meta$CTaa, "_", simplify = TRUE)[,2]
edit.distance <- 2

TCRA <- stringr::str_split(conga[[]]$CTaa, "_", simplify = TRUE)[,1]
TCRB <- stringr::str_split(conga[[]]$CTaa, "_", simplify = TRUE)[,2]
    
additions.TCRA <- lapply(confirm.TCRA, function(x) {
      pos <- which(stringdist(x, TCRA, method = "lv") <= edit.distance & 
                     stringdist(x, TCRA, method = "lv") > 0)
      pos
})

additions.TCRB <- lapply(confirm.TCRB, function(x) {
      pos <- which(stringdist(x, TCRB, method = "lv") <= edit.distance & 
                     stringdist(x, TCRB, method = "lv") > 0)
      pos
    })

conga@meta.data$confirmation.neighbors.TCRA <- NA
conga@meta.data$confirmation.neighbors.TCRB <- NA

for(i in seq_along(additions.TCRA)) {
  idx.A <- as.vector(conga@meta.data$TRAV[additions.TCRA[[i]]])
  idx.A <- which(idx.A == confirm.TCRA.gene[i])
  
  conga@meta.data$confirmation.neighbors.TCRA[additions.TCRA[[i]][idx.A]] <- paste0("TCR.", i)
}

for(i in seq_along(additions.TCRB)) {
   idx.B <- as.vector(conga@meta.data$TRBV[additions.TCRB[[i]]])
  idx.B <- which(idx.B == confirm.TCRB.gene[i])
  conga@meta.data$confirmation.neighbors.TCRB[additions.TCRB[[i]][idx.B]] <- paste0("TCR.", i)
}

meta <- conga[[]]
conga@meta.data$TCR.both <- paste0(conga@meta.data$confirmation.neighbors.TCRA, conga@meta.data$confirmation.neighbors.TCRB)
conga@meta.data$TCR.both[conga@meta.data$TCR.both == "NANA"] <- NA
conga@meta.data$TCR.both <- stringr::str_remove_all(conga@meta.data$TCR.both, "NA")
conga@meta.data$TCR.both[conga@meta.data$TCR.both == "TCR.1TCR.1"] <- "TCR.1"
conga@meta.data$TCR.both[conga@meta.data$TCR.both == "TCR.2TCR.2"] <- "TCR.2"

df <- data.frame(conga@reductions$phateTrex@cell.embeddings,
                  conga[[]])


df.sub <- subset(df, !is.na(confirmation.seq))
df.sub2 <- subset(df, !is.na(TCR.both))
write.csv(df.sub2, "Trex_edit.distance2_matchedVgenes.csv")

ggplot() +
    geom_point(data =df, aes(x=phateTrex_1, y = phateTrex_2, size = n), 
               fill = "grey", shape =21, stroke = 0.1) + 
  geom_point(data =df.sub2, aes(x=phateTrex_1, y = phateTrex_2, size = n, fill = TCR.both), shape =21, stroke = 0.1) + 
    geom_point(data = df.sub, aes(x=phateTrex_1, y = phateTrex_2, fill = confirmation.seq), 
               size = 4, shape =21, stroke = 0.2) + 
    scale_fill_manual(values = brewer.pal(5, "RdYlBu")) +
    theme_void()
#ggsave("added_edit.distance.png", height = 4, width = 5)

saveRDS(conga, "./data/processedData/conga_tfh_seuratObject.rds")
```

# Figure 4
```{r}
conga <- readRDS("./data/processedData/conga_tfh_seuratObject.rds")
conga$TCRA.COVID <- "No"
conga$TCRA.COVID[grepl("Spike", conga$TRA_Epitope.target)] <- "Yes"
conga$TCRA.COVID[!is.na(conga$TCRA.epitope)] <- "Yes"
conga$TCRA.COVID[!is.na(conga@meta.data$confirmation.neighbors.TCRA)] <- "Yes"
TCRA.ref <- data.frame("CTaa" = conga$CTaa, "COVID" = conga$TCRA.COVID)
TCRA.ref <- subset(TCRA.ref, COVID == "Yes")

conga$TCRB.COVID <- "No"
conga$TCRB.COVID[grepl("Spike", conga$TRB_Epitope.target)] <- "Yes"
conga$TCRB.COVID[!is.na(conga$TCRB.epitope)] <- "Yes"
conga$TCRB.COVID[!is.na(conga@meta.data$confirmation.neighbors.TCRB)] <- "Yes"
TCRB.ref <- data.frame("CTaa" = conga$CTaa, "COVID" = conga$TCRB.COVID)
TCRB.ref <- subset(TCRB.ref, COVID == "Yes")



SeuratObj <- readRDS("./data/processedData/Fullintegrated_seuratObjects_TFH_TFHonly.rds")

updated.shared.clones <- sort(unique(c(TCRB.ref$CTaa, TCRA.ref$CTaa)))
write.csv(updated.shared.clones, "./output/Spike.Specific.clones.csv")
dir.create("./output/Figure4")
```

Figure 4A

```{r}
SeuratObj <- subset(SeuratObj, timepoint != "d110")
subset.obj <- subset(SeuratObj, CTaa %in% updated.shared.clones)
subset.obj$timeline <- "Late"
subset.obj$timeline[subset.obj$timepoint %in% c("d28", "d60")] <- "Early"

Idents(subset.obj) <- "timeline"
EvL.markers <- FindMarkers(subset.obj, 
                           ident.1 = "Early",
                           test.use = "MAST", 
                           latent.vars = "donor", 
                           logfc.threshold = 0,
                           min.pct = 0,
                           pseudocount.use = 0.1)

write.csv(EvL.markers, "./output/Tfh.DEG.EarlyvsLate.csv")
EvL.markers <- EvL.markers %>%
                mutate(Percent.Delta = pct.1 - pct.2)
EvL.markers$genes <- rownames(EvL.markers)
rb.palette <- colorRampPalette(brewer.pal(11, "RdYlBu"))(11)

top10 <- EvL.markers %>% 
  subset(p_val < 0.05) %>%
  slice_max(order_by = avg_log2FC, n = 10)

bottom10 <- EvL.markers %>% 
  subset(p_val < 0.05) %>%
  slice_min(order_by = avg_log2FC, n = 10)

EvL.plot <- ggplot(EvL.markers, aes(x = avg_log2FC, y = -log10(p_val))) + 
  geom_point(aes(size = Percent.Delta), color = "grey") + 
  geom_point(data=subset(EvL.markers, genes %in% top10$genes),
             aes(size = Percent.Delta), color = rb.palette[1]) + 
  geom_point(data=subset(EvL.markers, genes %in% bottom10$genes),
             aes(size = Percent.Delta), color = rb.palette[11]) + 
  geom_text_repel(data=subset(EvL.markers, genes %in% c(top10$genes,bottom10$genes)), aes(label = genes), max.overlaps = 20) + 
  theme_classic() + 
  scale_size(range = c(0.1,3)) + 
  geom_hline(yintercept = 1.3) + 
  geom_vline(xintercept = 0)



Idents(subset.obj) <- "timepoint"
FvL.markers <- FindMarkers(subset.obj, 
                           ident.1 = "d28",
                           ident.2 = "d201",
                           test.use = "MAST", 
                           latent.vars = "donor", 
                           logfc.threshold = 0,
                           min.pct = 0,
                           pseudocount.use = 0.1)

write.csv(FvL.markers, "./output/Tfh.DEG.d28vsd201.csv")

FvL.markers <- FvL.markers %>%
                mutate(Percent.Delta = pct.1 - pct.2)
FvL.markers$genes <- rownames(FvL.markers)

top10 <- FvL.markers %>% 
  subset(p_val < 0.05) %>%
  slice_max(order_by = avg_log2FC, n = 10)

bottom10 <- FvL.markers %>% 
  subset(p_val < 0.05) %>%
  slice_min(order_by = avg_log2FC, n = 10)

FvL.plot <- ggplot(FvL.markers, aes(x = avg_log2FC, y = -log10(p_val))) + 
  geom_point(aes(size = Percent.Delta), color = "grey") + 
  geom_point(data=subset(FvL.markers, genes %in% top10$genes),
             aes(size = Percent.Delta), color = rb.palette[1]) + 
  geom_point(data=subset(FvL.markers, genes %in% bottom10$genes),
             aes(size = Percent.Delta), color = rb.palette[11]) + 
  geom_text_repel(data=subset(FvL.markers, genes %in% c(top10$genes,bottom10$genes)), aes(label = genes), max.overlaps = 20) + 
  theme_classic() + 
  scale_size(range = c(0.1,3)) + 
  geom_hline(yintercept = 1.3) + 
  geom_vline(xintercept = 0)

EvL.plot + FvL.plot + plot_layout(guides = "collect") & scale_size_continuous(limits = range(c(FvL.markers$Percent.Delta, EvL.markers$Percent.Delta)))
ggsave("./output/Figure4/Figure4A.pdf", height = 4.5, width = 10, dpi = 600)

```

```{r}
ES <- readRDS("./data/processedData/enrichmentResults.rds")
meta <- subset.obj[[]]

ES2 <- ES[rownames(ES) %in% rownames(meta),]
colnames(ES2) <- stringr::str_remove_all(colnames(ES2), "_UCell")
variances <- apply(ES2, 2, var)
#ES2 <- ES2[,-which(variances == 0)]

pathways <- colnames(ES2)

ES2 <- merge(ES2, meta, by = 0)

sig.results <- getSignificance(ES2, 
                               group = "timepoint", 
                               gene.sets = pathways, 
                               fit = "KW")
rownames(sig.results) <- stringr::str_remove_all(rownames(sig.results), "_UCell")

sig.results2 <- getSignificance(ES2, 
                               group = "timepoint", 
                               gene.sets = pathways, 
                               fit = "ANOVA")
rownames(sig.results2) <- stringr::str_remove_all(rownames(sig.results2), "_UCell")

KW.sig.pathways <- sig.results %>%
                        filter(p.value < 0.05) %>%
                        slice_max(order_by = Chi.square, n = 400) %>%
                        rownames() 

ANOVA.sig.pathways <- sig.results2 %>%
                        filter(p.value < 0.05) %>%
                        slice_max(order_by = f.value, n = 400) %>%
                        rownames()

pathways.intersect <- intersect(KW.sig.pathways, ANOVA.sig.pathways)
old.pathways <- read.csv("./output/int.pathways.csv")

pathways.intersect <- pathways.intersect[!grepl("REACTOME", pathways.intersect) ]
pathways.intersect <- pathways.intersect[-which(pathways.intersect %in% c( "BIOCARTA_FIBRINOLYSIS_PATHWAY", "BIOCARTA_AMI_PATHWAY", "BIOCARTA_EXTRINSIC_PATHWAY"))]


write(pathways.intersect, "output/Agspecific.intersected.pathways.txt")

summary <- ES2 %>%
  group_by(timepoint) %>%
  summarise(across(pathways.intersect, median))

normalize <- function(x) {
      (x- min(x)) /(max(x)-min(x))
}

for(i in 2:74) {
  summary[,i] <- normalize(summary[,i])
}
summary <- as.data.frame(summary)

rownames(summary) <- summary$timepoint



pdf("./output/Figure4/Figure4b.pdf", height = 10, width = 10)
pheatmap::pheatmap(t(summary[,2:74]))
dev.off()
```

Figure 4C 
```{r}
"%!in%" <- Negate("%in%")
dir.create("./output/Figure4")

SeuratObj <- readRDS("./data/processedData/Fullintegrated_seuratObjects_TFH_TFHonly.rds")
SeuratObj <- subset(SeuratObj, timepoint != "d110")

df <- unique(SeuratObj[[]][SeuratObj$CTaa %in% updated.shared.clones, c("CTaa", "timepoint")])
duplicated <- unique(df$CTaa[which(duplicated(df$CTaa))])
not.duplicated <- unique(df$CTaa[which(!duplicated(df$CTaa))])
not.duplicated <- not.duplicated[not.duplicated %!in% duplicated]


clone.palette <- colorRampPalette(brewer.pal(11, "RdYlBu"))(length(duplicated))

names(clone.palette) <- duplicated
pal2 <- rep("grey", length(not.duplicated))
names(pal2) <- not.duplicated
clone.palette <- c(clone.palette, pal2)

return.cc <- compareClonotypes(SeuratObj, 
                  clonotypes = unique(df$CTaa), 
                  split.by = "timepoint",
                  cloneCall="aa", 
                  graph = "alluvial",
                  exportTable = TRUE)

all.times <- c("d28", "d60", "d201")
output <- NULL
for(i in seq_along(duplicated)) {
  x <- return.cc[return.cc$Clonotypes == duplicated[i],]
  placement <- names(which(table(x$Sample) == 1))
  new.times <- all.times[all.times %!in% placement]
  rep.value <- length(new.times)
  y <- data.frame(Clonotypes = rep(duplicated[i], rep.value), Proportion = rep(0, rep.value), Sample = new.times)
  output <- rbind(output, y)
  
}
  return.cc <- unique(rbind(return.cc, output))
  return.cc$Sample <- factor(return.cc$Sample, levels = c("d28", "d60", "d201"))
  
  return.cc$Clonotypes <- factor(return.cc$Clonotypes, levels = names(clone.palette))
  ggplot(return.cc, aes(x = Sample, 
                        fill = Clonotypes, 
                        group = Clonotypes,
                        stratum = Clonotypes, 
                        alluvium = Clonotypes, 
                         y = Proportion, 
                        label = Clonotypes)) +
                theme_classic() +
                theme(axis.title.x = element_blank()) + 
                geom_stratum() +
                geom_flow(stat = "alluvium") + 
                guides(fill = "none")  + 
                scale_fill_manual(values = clone.palette)
  ggsave("./output/Figure4/Figure4C.pdf", height = 4, width = 6)
```

# Figure 6

```{r}
seuratObj <- readRDS("./data/processedData/Fullintegrated_seuratObjects_Tcells.rds")
seuratObj <- annotateDB(seuratObj, chains = "TRB", edit.distance = 0)
seuratObj <- annotateDB(seuratObj, chains = "TRA", edit.distance = 0)

seuratObj$TRAV <- stringr::str_split(seuratObj$CTgene, "[.]", simplify = TRUE)[,1]
seuratObj$TRBV <- stringr::str_split(seuratObj$CTgene, "_", simplify = TRUE)[,2]
seuratObj$TRBV <- stringr::str_split(seuratObj$TRBV, "[.]", simplify = TRUE)[,1]

meta <- conga[[]]
meta <- meta[!is.na(meta$confirmation.seq),]
meta <- meta[order(meta$confirmation.seq),]
confirm.TCRA.gene <- as.vector(meta$TRAV)
confirm.TCRB.gene <- as.vector(meta$TRBV)
confirm.TCRA <- stringr::str_split(meta$CTaa, "_", simplify = TRUE)[,1]
confirm.TCRB <- stringr::str_split(meta$CTaa, "_", simplify = TRUE)[,2]
edit.distance <- 2

write.csv(confirm.TCRA, "./output/TCRA.confirm.csv")
write.csv(confirm.TCRB, "./output/TCRB.confirm.csv")

TCRA <- stringr::str_split(seuratObj[[]]$CTaa, "_", simplify = TRUE)[,1]
TCRB <- stringr::str_split(seuratObj[[]]$CTaa, "_", simplify = TRUE)[,2]
    
additions.TCRA <- lapply(confirm.TCRA, function(x) {
      pos <- which(stringdist(x, TCRA, method = "lv") <= edit.distance & 
                     stringdist(x, TCRA, method = "lv") > 0)
      pos
})

additions.TCRB <- lapply(confirm.TCRB, function(x) {
      pos <- which(stringdist(x, TCRB, method = "lv") <= edit.distance & 
                     stringdist(x, TCRB, method = "lv") > 0)
      pos
    })

seuratObj@meta.data$confirmation.neighbors.TCRA <- NA
seuratObj@meta.data$confirmation.neighbors.TCRB <- NA

for(i in seq_along(additions.TCRA)) {
  idx.A <- as.vector(seuratObj@meta.data$TRAV[additions.TCRA[[i]]])
  idx.A <- which(idx.A == confirm.TCRA.gene[i])
  
  seuratObj@meta.data$confirmation.neighbors.TCRA[additions.TCRA[[i]][idx.A]] <- paste0("TCR.", i)
}

for(i in seq_along(additions.TCRB)) {
   idx.B <- as.vector(seuratObj@meta.data$TRBV[additions.TCRB[[i]]])
  idx.B <- which(idx.B == confirm.TCRB.gene[i])
  seuratObj@meta.data$confirmation.neighbors.TCRB[additions.TCRB[[i]][idx.B]] <- paste0("TCR.", i)
}



#Spike 167-180 epitope
sequence <- read.csv("./sequenceInfo/Sequences.csv")
CTaa <- as.data.frame(stringr::str_split(seuratObj$CTaa, "_", simplify = TRUE))
TA <- which(CTaa$V1 %in% sequence$cdr3a)
TB <-which(CTaa$V2 %in% sequence$cdr3b)

seuratObj$TCRB.S167.180<- NA
seuratObj$TCRB.S167.180[TB] <- "Specific"

seuratObj$TCRA.S167.180 <- NA
seuratObj$TCRA.S167.180[TA] <- "Specific"


#Spike 815-830 epitope

sequence <- read.csv("./sequenceInfo/dykema.sequences.csv")
CTaa <- as.data.frame(stringr::str_split(seuratObj$CTaa, "_", simplify = TRUE))
TA <-which(CTaa$V1 %in% sequence$cdr3a)
TB <-which(CTaa$V2 %in% sequence$cdr3b)

seuratObj$TCRB.S815.830 <- NA
seuratObj$TCRB.S815.830[TB] <- "Specific"

seuratObj$TCRA.S815.830 <- NA
seuratObj$TCRA.S815.830[TA] <- "Specific"

# VDJdb sequence

sequences <- read.delim("./sequenceInfo/VDJdb.tsv")
sequences <- sequences[sequences$MHC.class == "MHCII" & sequences$Epitope.gene == "Spike",]

epitope <- c("NCTFEYVSQPFLMDL" = "S164.179",
"RISNCVADYSVLYNS" = "S356.371",
"NFSQILPDPSKPSKR" = "S800.815",
"HWFVTQRNFYEPQII" = "S1101.1115",
"VGGNYNYLYRLFRKS" = "S445.459",
"NNSYECDIPIGAGIC" = "S657.671")

seuratObj$TCRB.VDJ.db <- NA
seuratObj$TCRA.VDJ.db <- NA
for (i in seq_along(epitope)) {
  sequences$Epitope[which(sequences$Epitope == names(epitope)[i])] <- epitope[i]
  TA <- sequences[sequences$Gene == "TRA" & sequences$Epitope == epitope[i], ]
  TB <- sequences[sequences$Gene == "TRB" & sequences$Epitope == epitope[i], ]
  TA.loc <-which(CTaa$V1 %in% TA$CDR3)
  TB.loc <-which(CTaa$V2 %in% TB$CDR3)
  seuratObj$TCRB.VDJ.db[TB.loc] <- epitope[i]
  seuratObj$TCRA.VDJ.db[TA.loc] <- epitope[i]
}


seuratObj$TCRB.epitope  <- NA
seuratObj$TCRB.epitope <- ifelse(!is.na(seuratObj$TCRB.S167.180), "S167.180", NA)
seuratObj$TCRB.epitope <- ifelse(!is.na(seuratObj$TCRB.S815.830), "S815.830", seuratObj$TCRB.epitope)
seuratObj$TCRB.epitope <- ifelse(!is.na(seuratObj$TCRB.VDJ.db) & is.na(seuratObj$TCRB.epitope), seuratObj$TCRB.VDJ.db, seuratObj$TCRB.epitope)

seuratObj$TCRA.epitope  <- NA
seuratObj$TCRA.epitope <- ifelse(!is.na(seuratObj$TCRA.S167.180), "S167.180", NA)
seuratObj$TCRA.epitope <- ifelse(!is.na(seuratObj$TCRA.S815.830), "S815.830", seuratObj$TCRA.epitope)
seuratObj$TCRA.epitope <- ifelse(!is.na(seuratObj$TCRA.VDJ.db) & is.na(seuratObj$TCRA.epitope), seuratObj$TCRA.VDJ.db, seuratObj$TCRA.epitope)

seuratObj$TCRA.COVID <- "No"
seuratObj$TCRA.COVID[grepl("Spike", seuratObj$TRA_Epitope.target)] <- "Yes"
seuratObj$TCRA.COVID[!is.na(seuratObj$TCRA.epitope)] <- "Yes"
seuratObj$TCRA.COVID[!is.na(seuratObj$confirmation.neighbors.TCRA)] <- "Yes"
TCRA.ref <- data.frame("CTaa" = seuratObj$CTaa, "COVID" = seuratObj$TCRA.COVID)
TCRA.ref <- subset(TCRA.ref, COVID == "Yes")

seuratObj$TCRB.COVID <- "No"
seuratObj$TCRB.COVID[grepl("Spike", seuratObj$TRB_Epitope.target)] <- "Yes"
#seuratObj$TCRB.COVID[!is.na(seuratObj$TCRB.epitope)] <- "Yes"
seuratObj$TCRB.COVID[!is.na(seuratObj$confirmation.neighbors.TCRB)] <- "Yes"
TCRB.ref <- data.frame("CTaa" = seuratObj$CTaa, "COVID" = seuratObj$TCRB.COVID)
TCRB.ref <- subset(TCRB.ref, COVID == "Yes")

overall.spike.specific.tcells <- write.csv(unique(c(TCRA.ref$CTaa, TCRB.ref$CTaa)), "./output/spike.clones_overall.csv")

subset.Obj <- subset(seuratObj, CTaa %in% unique(c(TCRA.ref$CTaa, TCRB.ref$CTaa)))
subset.Obj <- subset(subset.Obj, CD8.pos == "No")
subset.Obj <- subset(subset.Obj, timepoint != "d110")
dir.create("./output/Figure6")
```

# Figure 6A

```{r}
Idents(subset.Obj) <- "tissue"
LNvB.markers <- FindMarkers(subset.Obj, 
                           ident.1 = "LN",
                           test.use = "MAST", 
                           latent.vars = c("donor"), 
                           logfc.threshold = 0,
                           min.pct = 0,
                           pseudocount.use = 0.1)

write.csv(LNvB.markers, "./output/Ag.specific.LNvsBLcsv")
LNvB.markers <- LNvB.markers %>%
                mutate(Percent.Delta = pct.1 - pct.2)
LNvB.markers$genes <- rownames(LNvB.markers)
rb.palette <- colorRampPalette(brewer.pal(11, "RdYlBu"))(11)

top10 <- LNvB.markers %>% 
  subset(p_val < 0.05) %>%
  slice_max(order_by = avg_log2FC, n = 10)

bottom10 <- LNvB.markers %>% 
  subset(p_val < 0.05) %>%
  slice_min(order_by = avg_log2FC, n = 10)

LNvBL.plot <- ggplot(LNvB.markers, aes(x = avg_log2FC, y = -log10(p_val))) + 
  geom_point(aes(size = Percent.Delta), color = "grey") + 
  geom_point(data=subset(LNvB.markers, genes %in% top10$genes),
             aes(size = Percent.Delta), color = rb.palette[1]) + 
  geom_point(data=subset(LNvB.markers, genes %in% bottom10$genes),
             aes(size = Percent.Delta), color = rb.palette[11]) + 
  geom_text_repel(data=subset(LNvB.markers, genes %in% c(top10$genes,bottom10$genes)), aes(label = genes), max.overlaps = 20) + 
  theme_classic() + 
  scale_size(range = c(0.1,3)) + 
  geom_hline(yintercept = 1.3) + 
  geom_vline(xintercept = 0)
ggsave("./output/Figure6/Figure6A.png", height = 4.5, width = 5, dpi = 600)
```

```{r}
meta <- subset.Obj[[]]

ES2 <- ES[rownames(ES) %in% rownames(meta),]
colnames(ES2) <- stringr::str_remove_all(colnames(ES2), "_UCell")
variances <- apply(ES2, 2, var)
#ES2 <- ES2[,-which(variances == 0)]

pathways <- colnames(ES2)

ES2 <- merge(ES2, meta, by = 0)

sig.results <- getSignificance(ES2, 
                               group = "tissue", 
                               gene.sets = pathways, 
                               fit = "Wilcoxon")

sig.results2 <- getSignificance(ES2, 
                               group = "tissue", 
                               gene.sets = pathways, 
                               fit = "T.test")

W.sig.pathways <- sig.results %>%
                        filter(p.value < 0.05) %>%
                        slice_max(order_by = W.statistic, n = 200) %>%
                        rownames() 

T.sig.pathways <- sig.results2 %>%
                        filter(p.value < 0.05) %>%
                        slice_max(order_by = T.statistic, n = 200) %>%
                        rownames()

pathways.intersect <- intersect(W.sig.pathways, T.sig.pathways)
old.pathways <- read.csv("./output/int.pathways.csv")

pathways.intersect <- pathways.intersect[!grepl("REACTOME", pathways.intersect) ]
write(pathways.intersect, "./output/Figure6_Agspecific.intersected.pathways.txt")

ES2$timetissue <- paste0(ES2$timepoint, "_", ES2$tissue)
summary <- ES2 %>%
  group_by(timetissue) %>%
  summarise(across(pathways.intersect, median))


normalize <- function(x) {
      (x- min(x)) /(max(x)-min(x))
}

for(i in 2:40) {
  summary[,i] <- normalize(summary[,i])
}
summary <- as.data.frame(summary)

rownames(summary) <- summary$timetissue



pdf("./output/Figure6/Figure6b.pdf", height = 8, width = 14)
pheatmap::pheatmap(t(summary[,2:40]))
dev.off()
```